theme: jekyll-theme-cayman
title: Predicting Survival and Controlling for Biased with Random Survival Forests and Condtional Inference Forests Using Right-Censored Data 
description: Written by Nancy Liu & Breanna Richards
